/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sifry;

/**
 *
 * @author saljack
 */
public class Main {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String[] str = new String[9];
        str[0] = "ZEOBJDECBZVAIZVNISZKXOXQXEJZEAIFZSAIXBXRKFIXFIROOMXPVXXEDECXXCRECIRQXROOFIXODTXFAZXRAROOAIXNZLEFFIXODTXFAZNXAROOAIXHZJUREBFIXODTXFAZTXXURECXQXKBAIDENIXKIXRKACXFDKXFDEAIXALXOSAIJZEAIFIXJVFAFXAAZLZKTRECFUDESDQXFTXDEFRCRBRECDSFIXCZXFEZAFIXJVFACDX";

        str[1] = "IKHODRDTALAQBADJRKTCOHKTCOQABQOOSRCOTCKUBCTWCATABQAJSHAQQDABODTWARNKQCOQSAUBCTOQAJSARNKQTCONDVORFODJRTDHOOJKUBCTKLKTCOQALKUTTCOHWCOJTCOYOAQIAHOQKUJSTCOQOWARHAJYARGDMLOTWOOJIUMAJSGDMAJSGDFOGYARJKTTCOFDJBWKUGSCAVONKQBKTTOJAGGALKUTDTLYTCOJAJYCKWCOQSAUBCTOQWKUGSLOPUOOJNKQOGOVOJHKJTCR";

        str[2] = "KWWLAYHOJMPENRTOVIQHBOCODMYIJMZXLPVXDEMBALHAWSSKHXBEOHLZHGFSQLOLWAKIDAOONMUCPHTXYAKIHIVOVBRIWTLXVIOPPHPQGEQWOHPVASHHPOROLIOPPHPMGUSEJYDRWKDVADEYCMHTWNOONMUCPHTXYPHVDELBLLHWERPNSVGLARSEKJDRZTSOCQQKSADUAVGEOKTXVKRYHDMOTCWMJTSOLMQXDMZXLPVLABPQSVWSPHTXCWIXDODOXQYIOKPSFADRZWZXVMUMBTSOCQQKNEXOEJHVADLXVQQXDEPVWDHRPHXYFBKWDEMOYIQXKDCOSUDFKUEDZMPEOWPVD";

        str[3] = "ENBTUOWEARDIRDDIKTEHRENHGABHSUYANSDTUAOBSMTEHHEOHSHDOEPFDEAHTOOGRxxTNE";

        str[4] = "BLEHUIHYTWNUSLUALTSNAEHAOTPXTSEHBTDSANTAIXOTVEAONODDHSNXNDEKNAENOTITNXTANIDRVBNHNOIXHYTNLOEEEEGONXEOHGEORFWRILGXVFMHDMSOIENAWXETOEHSERNWINHXRHNREHTEDATDEXYETHREEIOSBAEX";

        str[5] = "WRDKKIHEOOWMUDLIEONNKODOXYEUNYLTERNTVLOXBIHTIIRIEXOAIEIWSHMMGOTNFDVYEUSYACFMHQIELURRRIEASAFNUOFEUWMXNEATLUENOWNSCAENEGVPESELFDSIDOBITOIHISMAYNASVNHLOX";

        str[6] = "WALSOEWIFTEOEORHHSTHMABTLCEUHTOMHONDSLDSCDCETOPRWSLLENQXHTESNEESRORFIXHANLEEYRAHOSXXTHUEVNEETOODFXHDEHHAITSOAREXTOSIELVSFRRRUXLHNSWGAWNWEHGXYRLTTEALOEISSXOELLSNODEHSUNXUTHANWLFHANTWXELASIRAHHRORNXNGGDEERTFEAOUXEDEPRHSGOHAOEXIAAHTEOSEHSOTX";

        str[7] = "IHJDUKHTTEIUYBXDHHEIQOZHDUUCYJBJMSFXQTJUUQYMXHDQTETHXXUJXXBHIBXKUUTDUTEXUIVESUJEXHAJQXUTDXEEETOIESXSQTBHUEYX";

        str[8] = "WOTJLONLTEEOJETETXOLGEWRTXGWWXBELOTXEHBVBWTEXOTXHEWKOAKXJTUTKEEJEXOHZRLXVHGARJXEHXZAUORJHHBZHLDXHHRPXJCWEEEKHOLZOEEEXFWXJJLDHKXCXGTTLXOHXORBTWFX";
        Desifrovani des = new Desifrovani();
//        for (int i = 0; i < str.length; ++i) {
//            System.out.println(i+": "+des.IC(str[i]));
//            des.prostyPosun(str[i]);
//            System.out.println("\n\n\n\n\n\n\n");
//        }
//        des.affini(str[0]);
//        Desifrovani.substituceSKlicem("fsafdsdf", "HESLO");
        MainWindow mw = new MainWindow();
        mw.setVisible(true);

    }
}
